### ISSUE TITLE
Moving the fleet

### ISSUE THREAD

**Issue by richjoregonstate** [cs361w2019-osu/sprint1-group-10#100]
- [x] Recall the place ship function on all ships with an offset of NESW
- [x] Check to see if any ship would fall off the edge if so no movement
- [x] If the above happens then you need to check to see if the nonmovement of the first ship causes an overlap
- [x] Add a check to make sure that this can only be done after two ships have been sunk.

**Comment by yorkal** [comment]
Fleets moves, doesn't go over the edge, and only moves twice. Good!
