### ISSUE TITLE
Design Details WIKI page

### ISSUE THREAD

**Issue by richjoregonstate** [cs361w2019-osu/sprint1-group-10#47]
We need to fill out the page with the following information:

- [ ] Target platform
- [ ] Input method
- [ ] Type of user

It will also need
- [ ] Final design layout on paper 
- [ ] Blank state of the webpage
- [ ] Regular state of the webpage
- [ ] Error state of the webpage

**Comment by jctrotter** [comment]
Finished, updated the wiki page.
