### ISSUE TITLE
Usability wiki page

### ISSUE THREAD

**Issue by richjoregonstate** [cs361w2019-osu/sprint1-group-10#48]
Need section on how our design does the following:

- [ ] Learnability: How easy is it for users to accomplish basic tasks the first time they encounter the design?
- [ ] Efficiency: Once users have learned the design, how quickly can they perform tasks?
- [ ] Memorability: When users return to the design after a period of not using it, how easily can they reestablish proficiency?
- [ ] Errors: How many errors do users make, how severe are these errors, and how easily can they recover from the errors?
- [ ] Satisfaction: How pleasant is it to use the design?

**Comment by jctrotter** [comment]
Done, updated the usability page.
