### ISSUE TITLE
Implment double hit and sink for destroyer and battleship

### ISSUE THREAD

**Issue by richjoregonstate** [cs361w2019-osu/sprint1-group-10#85]
The captains quarters for battleships and destroyers (but not minesweepers!) is armored, so it takes 2 attacks on the same square for it to "hit"

- [ ] Make a new result type so the user knows they hit a captains quarters.
- [ ] When the captain's quarters is hit a second-time register hits for the rest of the ship so it looks sunk & sink the ship

Warning: You'll need to figure out how to make sure the double hit tags in the css & html don't conflict.

**Comment by jctrotter** [comment]
Done, implemented in the project.
