### ISSUE TITLE
Implment sonar

### ISSUE THREAD

**Issue by richjoregonstate** [cs361w2019-osu/sprint1-group-10#86]
A new special weapon has been introduced: the "sonar pulse." The sonar pulse allows a player to reveal a portion of the map, as shown in the figure below. The sonar pulse merely reveals the status of the cell as being free (shown as gray) or occupied (shown as black). It does not reveal the location of the ship's captain's quarters. A player can use a total of two (2) sonar pulses in a game, only after successfully sinking the first enemy ship.

- [x] Create two new results types empty & nonempty
- [x] Implement checks for a ship has been sunk before allowing the event to happen
- [x] Add button & update javascript
- [x] Add graphic for the sonar pulse

This is bound to take me two days wed-thur

**Comment by jctrotter** [comment]
Done by Jon, implemented in the project.
