### ISSUE TITLE
Refactor to OO code

### ISSUE THREAD

**Issue by richjoregonstate** [cs361w2019-osu/sprint1-group-10#87]
Refactor to Object-Oriented Design. Using code smells, identify places in your code that require refactoring. Using OO principles such as Inheritance, Polymorphism and Encapsulation, refactor the Battlehip codebase (including the new features, if applicable), making sure your design respects the SOLID design principles. Be careful with your design, since the next sprint will include several new features that rely upon having a good OO foundation to build upon.

**Comment by jctrotter** [comment]
Done, implemented in the project.
