### ISSUE TITLE
New ship submarine

### ISSUE THREAD

**Issue by richjoregonstate** [cs361w2019-osu/sprint1-group-10#98]
- [x] Add a frontend button to trigger placement.
- [x] Add a checkbox for below water
- [x] In board.placeShip() Alter the code to change the occupied squares of the sub so that it can do proper out of bounds check.
- [x] Remove the overlap check as the sub can be under ships
- [x] Modify the overlap check so that other ships ignore the sub
- [x] Modify board.atack() to handle the captains quarters of the sub

**Comment by yorkal** [comment]
The submarine works!
